/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is the API up? */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Is the database reachable? */
        get: operations["healthDb"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List books (search, filter, sort, page) */
        get: operations["listBooks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One book with its public ratings */
        get: operations["getBook"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All categories with how many books each has */
        get: operations["listCategories"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/languages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Book languages with counts */
        get: operations["listLanguages"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            ok: boolean;
            service: string;
            /** Format: date-time */
            time: string;
        };
        DbHealth: {
            ok: boolean;
            database: string;
            now: string;
            ms: number;
        };
        BookPage: {
            items: components["schemas"]["Book"][];
            page: number;
            pageSize: number;
            total: number;
            pages: number;
        };
        Book: {
            /** Format: uuid */
            id: string;
            /** @example මඩොල් දූව */
            title: string;
            /** @example Madol Doova */
            titleSinglish: string | null;
            author: string | null;
            authorSinglish: string | null;
            /** @example Sinhala */
            language: string | null;
            isTranslation: boolean;
            translator: string | null;
            originalTitle: string | null;
            originalAuthor: string | null;
            isbn: string | null;
            publisher: string | null;
            year: number | null;
            description: string | null;
            reviewSummary: string | null;
            webSources: {
                title: string;
                url: string;
            }[] | null;
            coverUrl: string | null;
            copies: number;
            shelf: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /**
             * @example [
             *       "Novel",
             *       "Classic"
             *     ]
             */
            categories: string[];
            /** @description copies minus open loans */
            available: number;
            /** @example 4.5 */
            avgRating: number | null;
            ratingCount: number;
        };
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Bad Request */
            title: string;
            /** @example 400 */
            status: number;
            /** @example pageSize: Too big: expected number to be <=100 */
            detail?: string;
            errors?: {
                field: string;
                message: string;
            }[];
        };
        BookDetail: components["schemas"]["Book"] & {
            ratings: components["schemas"]["PublicRating"][];
        };
        PublicRating: {
            rating: number;
            review: string | null;
            /** @description the reader's name (never the email) */
            name: string | null;
            /** Format: date-time */
            updatedAt: string;
        };
        Category: {
            id: number;
            name: string;
            bookCount: number;
        };
        Language: {
            language: string | null;
            bookCount: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    healthDb: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DbHealth"];
                };
            };
        };
    };
    listBooks: {
        parameters: {
            query?: {
                /** @description Search title, author, translator… (Sinhala, English or Singlish) */
                q?: string;
                language?: string;
                /** @description Repeat for several: ?category=Novel&category=War (a book needs at least one) */
                category?: string | string[];
                /** @description true = only translated books */
                translations?: "true" | "false";
                /** @description true = only books with a free copy */
                available?: "true" | "false";
                sort?: "title" | "newest" | "rating";
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of books */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookPage"];
                };
            };
            /** @description The query string is not valid */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getBook: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The book */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BookDetail"];
                };
            };
            /** @description The id is not a valid UUID */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No book with this id */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listCategories: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Categories A–Z */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Category"][];
                };
            };
        };
    };
    listLanguages: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Languages A–Z */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Language"][];
                };
            };
        };
    };
}
